MVC-plenum-2/Models/DBContext.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Data.Entity;
using System.Data.Entity.ModelConfiguration.Conventions;
using System.Linq;
using System.Web;

namespace MVC_plenum_2.Models
{

    public class Kunder
    {
         public int ID { get; set; }
         public string Fornavn { get; set; }
         public string Etternavn { get; set; }
         public string Adresse { get; set; }
         public string Postnr { get; set; }

         public virtual Poststeder Poststeder {get;set;} 
    }
    public class Poststeder
    {
        public string Postnr { get; set; }
        public string Poststed { get; set; }

        public virtual List<Kunder> Kunder { get; set; }
    }

    public class KundeContext : DbContext
    {
        public KundeContext()
            : base("name=Kunder")
        {
            Database.CreateIfNotExists();
        }
        
        public DbSet<Kunder> Kunder { get; set; }
        public DbSet<Poststeder> Poststeder { get; set; }

        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            modelBuilder.Entity<Poststeder>()
                        .HasKey(p => p.Postnr);
            modelBuilder.Conventions.Remove<PluralizingTableNameConvention>();
        }
    }
}

MVC-plenum-2/Models/Kunde.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations; // denne må være med!
using System.Linq;
using System.Web;

namespace MVC_plenum_2.Models
{
    public class Kunde
    {
        // dette er både en domenemodell og en view-modell
        public int id { get; set; }

        [Display(Name = "Fornavn")]
        [Required(ErrorMessage = "Fornavn må oppgis")]
        public string fornavn { get; set; }
        
        [Display(Name = "Etternavn")]
        [Required(ErrorMessage = "Etternavn må oppgis")]
        public string etternavn { get; set; }
        
        [Display(Name = "Adresse")]
        [Required(ErrorMessage = "Adressen må oppgis")]
        public string adresse { get; set; }

        [Display(Name = "Postnr")]
        [Required(ErrorMessage = "Postnr må oppgis")]
        [RegularExpression(@"[0-9]{4}", ErrorMessage = "Postnr må være 4 siffer")]
        public string postnr { get; set; }
        
        [Display(Name = "Poststed")]
        [Required(ErrorMessage = "Poststed må oppgis")]
        public string poststed { get; set; }
    }
}

MVC-plenum-2/Controllers/KundeController.cs
using MVC_plenum_2.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MVC_plenum_2.Controllers
{
    public class KundeController : Controller
    {
        public ActionResult Liste()
        {
            var kundeDb = new DBKunde();
            List<Kunde> alleKunder = kundeDb.hentAlle();
            return View(alleKunder);
        }

        public ActionResult Detaljer(int id)
        {
            var kundeDb = new DBKunde();
            Kunde enKunde = kundeDb.hentEnKunde(id);
            return View(enKunde);
        }

        public ActionResult Registrer()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Registrer(Kunde innKunde)
        {
            if (ModelState.IsValid)
            {
                var kundeDb = new DBKunde();
                bool insertOK = kundeDb.settInn(innKunde);
                if (insertOK)
                {
                    return RedirectToAction("Liste");
                }
            }
            return View();
        }

        public ActionResult Endre(int id)
        {
            var kundeDb = new DBKunde();
            Kunde enKunde = kundeDb.hentEnKunde(id);
            return View(enKunde);
        }

        [HttpPost]
        public ActionResult Endre(int id, Kunde endreKunde)
        {

            if (ModelState.IsValid)
            {
                var kundeDb = new DBKunde();
                bool endringOK = kundeDb.endreKunde(id, endreKunde);
                if (endringOK)
                {
                    return RedirectToAction("Liste");
                }
            }
            return View();
        }

        public ActionResult Slett(int id)
        {
            var kundeDb = new DBKunde();
            Kunde enKunde = kundeDb.hentEnKunde(id);
            return View(enKunde);
        }

        [HttpPost]
        public ActionResult Slett(int id, Kunde slettKunde)
        {
            var kundeDb = new DBKunde();
            bool slettOK = kundeDb.slettKunde(id);
            if(slettOK)
            {
                return RedirectToAction("Liste");
            }
            return View();
        }
    }
}

MVC-plenum-2/Views/Kunde/Detaljer.cshtml
@model MVC_plenum_2.Models.Kunde

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Detaljer</title>
</head>
<body>
    <div>
        <h4>Kunde</h4>
        <hr />
        <dl class="dl-horizontal">
            <dt>
                @Html.DisplayNameFor(model => model.fornavn)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.fornavn)
            </dd>
    
            <dt>
                @Html.DisplayNameFor(model => model.etternavn)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.etternavn)
            </dd>
    
            <dt>
                @Html.DisplayNameFor(model => model.adresse)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.adresse)
            </dd>
    
            <dt>
                @Html.DisplayNameFor(model => model.postnr)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.postnr)
            </dd>
    
            <dt>
                @Html.DisplayNameFor(model => model.poststed)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.poststed)
            </dd>
    
        </dl>
    </div>
    <p>
        @Html.ActionLink("Endre", "Endre", new { id = Model.id }, new { @class = "btn btn-success" }) 
        @Html.ActionLink("Kundeliste", "Liste", new { tom = "" }, new { @class = "btn btn-primary" })
    </p>
</body>
</html>

MVC-plenum-2/Views/Kunde/Endre.cshtml
@model MVC_plenum_2.Models.Kunde

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Endre</title>
</head>
<body>
    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()
        
        <div class="form-horizontal">
            <h4>Kunde</h4>
            <hr />
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            @Html.HiddenFor(model => model.id)
    
            <div class="form-group">
                @Html.LabelFor(model => model.fornavn, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.fornavn, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.fornavn, "", new { @class = "text-danger" })
                </div>
            </div>
    
            <div class="form-group">
                @Html.LabelFor(model => model.etternavn, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.etternavn, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.etternavn, "", new { @class = "text-danger" })
                </div>
            </div>
    
            <div class="form-group">
                @Html.LabelFor(model => model.adresse, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.adresse, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.adresse, "", new { @class = "text-danger" })
                </div>
            </div>
    
            <div class="form-group">
                @Html.LabelFor(model => model.postnr, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.postnr, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.postnr, "", new { @class = "text-danger" })
                </div>
            </div>
    
            <div class="form-group">
                @Html.LabelFor(model => model.poststed, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.poststed, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.poststed, "", new { @class = "text-danger" })
                </div>
            </div>
    
            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Lagre" class="btn btn-success" />
                    @Html.ActionLink("Kundeliste", "Liste", new { tom = "" }, new { @class = "btn btn-primary" })
                </div>
            </div>
        </div>
    }
</body>
</html>

MVC-plenum-2/Views/Kunde/Liste.cshtml
@model List<MVC_plenum_2.Models.Kunde>

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Liste</title>
</head>
<body>
    <br/><br/>
    <table class="table">
        <tr>
            <th>
                @Html.DisplayNameFor(model => model[0].fornavn) 
                <!-- NB: dette er endret fra generert kode da den forventer en IEnumerable som modell -->
            </th>
            <th>
                @Html.DisplayNameFor(model => model[0].etternavn)
            </th>
            <th>
                @Html.DisplayNameFor(model => model[0].adresse)
            </th>
            <th>
                @Html.DisplayNameFor(model => model[0].postnr)
            </th>
            <th>
                @Html.DisplayNameFor(model => model[0].poststed)
            </th>
            <th></th>
        </tr>
    
    @foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.fornavn)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.etternavn)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.adresse)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.postnr)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.poststed)
            </td>
            <td>
                @Html.ActionLink("Endre", "Endre", new { id = item.id }, new { @class = "btn btn-success" }) 
                @Html.ActionLink("Detalj", "Detaljer", new { id = item.id }, new { @class = "btn btn-primary" }) 
                @Html.ActionLink("Slette", "Slett", new { id = item.id }, new { @class = "btn btn-danger" })
            </td>
        </tr>
    }
    
    </table>
    @Html.ActionLink("Registrer", "Registrer", new { tom = "" }, new { @class = "btn btn-success" })
</body>
</html>

MVC-plenum-2/Views/Kunde/Registrer.cshtml
@model MVC_plenum_2.Models.Kunde

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Registrer</title>
</head>
<body>
    @using (Html.BeginForm()) 
    {
        @Html.AntiForgeryToken()
        
        <div class="form-horizontal">
            <h4>Kunde</h4>
            <hr />
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            <div class="form-group">
                @Html.LabelFor(model => model.fornavn, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.fornavn, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.fornavn, "", new { @class = "text-danger" })
                </div>
            </div>
    
            <div class="form-group">
                @Html.LabelFor(model => model.etternavn, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.etternavn, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.etternavn, "", new { @class = "text-danger" })
                </div>
            </div>
    
            <div class="form-group">
                @Html.LabelFor(model => model.adresse, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.adresse, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.adresse, "", new { @class = "text-danger" })
                </div>
            </div>
    
            <div class="form-group">
                @Html.LabelFor(model => model.postnr, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.postnr, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.postnr, "", new { @class = "text-danger" })
                </div>
            </div>
    
            <div class="form-group">
                @Html.LabelFor(model => model.poststed, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.poststed, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.poststed, "", new { @class = "text-danger" })
                </div>
            </div>
    
            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Lagre" class="btn btn-success" />
                    @Html.ActionLink("Kundeliste", "Liste", new { tom = "" }, new { @class = "btn btn-primary" })
                </div>
            </div>
        </div>
    }
</body>
</html>

MVC-plenum-2/Views/Kunde/Slett.cshtml
@model MVC_plenum_2.Models.Kunde

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Slett</title>
</head>
<body>
     <br/><br/>   
     <h3>Er du sikker på at du vil slette denne?</h3>
    <div>
        <h4>Kunde</h4>
        <hr />
        <dl class="dl-horizontal">
            <dt>
                @Html.DisplayNameFor(model => model.fornavn)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.fornavn)
            </dd>
    
            <dt>
                @Html.DisplayNameFor(model => model.etternavn)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.etternavn)
            </dd>
    
            <dt>
                @Html.DisplayNameFor(model => model.adresse)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.adresse)
            </dd>
    
            <dt>
                @Html.DisplayNameFor(model => model.postnr)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.postnr)
            </dd>
    
            <dt>
                @Html.DisplayNameFor(model => model.poststed)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.poststed)
            </dd>
    
        </dl>
    
        @using (Html.BeginForm()) {
            @Html.AntiForgeryToken()
    
            <div class="form-actions no-color">
                <input type="submit" value="Slett" class="btn btn-danger" /> 
                @Html.ActionLink("Kundeliste", "Liste", new { tom = "" }, new { @class = "btn btn-primary" })
            </div>
        }
    </div>
</body>
</html>

MVC-plenum-2/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Kunderegistering</title>
    <script src="~/Scripts/jquery-1.9.0.js"></script>
    <script src="~/Scripts/jquery.validate.js"></script>
    <script src="~/Scripts/jquery.validate.unobtrusive.js"></script>
    <link href="~/Content/bootstrap.css" rel="stylesheet" />
    <link href="~/Content/bootstrap-theme.css" rel="stylesheet" />
    <script src="~/Scripts/bootstrap.js"></script>

</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Kunderegister", "Liste", "Kunde", new { tom = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Kundeliste", "Liste", "Kunde")</li>
                    <li>@Html.ActionLink("Registrer", "Registrer", "Kunde")</li>
                </ul>
            </div>
        </div>
    </div>
    <br/>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p> &copy;@DateTime.Now.Year -HiOA Informasjonsteknologi <p>
        </footer>
    </div>
</body>
</html>